name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - feature/test-reports

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet '7.0.x'  
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml

      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
  
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;logfilename=test-results.trx"

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: ./Generator.Tests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Push generated package 'Genarator' to nuget.org registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: dotnet nuget push ./Generator/bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}